# Generated by Django 5.1.6 on 2025-02-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jenis_tanaman', models.CharField(max_length=100)),
                ('lokasi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KetuaKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua', to='administrator.grup')),
            ],
        ),
        migrations.CreateModel(
            name='KesehatanTanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi', models.CharField(max_length=100)),
                ('penyakit', models.TextField(blank=True, null=True)),
                ('tindakan', models.TextField()),
                ('lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.lahan')),
            ],
        ),
        migrations.CreateModel(
            name='KesehatanTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_tanah', models.DecimalField(decimal_places=1, max_digits=3)),
                ('kadar_air', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nutrisi', models.TextField()),
                ('lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.lahan')),
            ],
        ),
        migrations.CreateModel(
            name='Petani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='administrator.grup')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.ketuakelompok')),
            ],
        ),
        migrations.AddField(
            model_name='lahan',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.petani'),
        ),
        migrations.CreateModel(
            name='DistribusiPupuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pupuk', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('tanggal_distribusi', models.DateField()),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.petani')),
            ],
        ),
    ]
