# Generated by Django 5.1.6 on 2025-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribusipupuk',
            options={'verbose_name_plural': 'Data Distribusi Pupuk'},
        ),
        migrations.AlterModelOptions(
            name='grup',
            options={'verbose_name_plural': 'Data Grup'},
        ),
        migrations.AlterModelOptions(
            name='kesehatantanah',
            options={'verbose_name_plural': 'Data Kesehatan Tanah'},
        ),
        migrations.AlterModelOptions(
            name='kesehatantanaman',
            options={'verbose_name_plural': 'Data Kesehatan Tanaman'},
        ),
        migrations.AlterModelOptions(
            name='ketuakelompok',
            options={'verbose_name_plural': 'Data Ketua Kelompok'},
        ),
        migrations.AlterModelOptions(
            name='lahan',
            options={'verbose_name_plural': 'Data Lahan'},
        ),
        migrations.AlterModelOptions(
            name='petani',
            options={'verbose_name_plural': 'Data Petani'},
        ),
        migrations.AddField(
            model_name='distribusipupuk',
            name='gambar_distribusi',
            field=models.ImageField(null=True, upload_to='gambar/distribusi'),
        ),
        migrations.AddField(
            model_name='kesehatantanah',
            name='gambar_tanah',
            field=models.ImageField(null=True, upload_to='gambar/tanah'),
        ),
        migrations.AddField(
            model_name='kesehatantanaman',
            name='gambar_tanaman',
            field=models.ImageField(null=True, upload_to='gambar/tanaman'),
        ),
    ]
