# Generated by Django 5.1.6 on 2025-02-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_distribusipupuk_options_alter_grup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='gambar_lahan',
            field=models.ImageField(null=True, upload_to='gambar/lahan'),
        ),
    ]
