# Generated by Django 5.1.6 on 2025-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_lahan_gambar_lahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petani',
            name='kelompok',
        ),
        migrations.AddField(
            model_name='distribusipupuk',
            name='satuan',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton')], default='kg', max_length=3),
        ),
    ]
