# Generated by Django 5.1.6 on 2025-03-02 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_distribusipupuk_satuan_distribusipupuk_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesehatantanaman',
            name='penyakit',
        ),
        migrations.RemoveField(
            model_name='kesehatantanaman',
            name='tindakan',
        ),
        migrations.AddField(
            model_name='kesehatantanaman',
            name='isi_penyakit_dan_tindakan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribusipupuk',
            name='jenis_pupuk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesehatantanah',
            name='nutrisi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ketuakelompok',
            name='alamat',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lahan',
            name='lokasi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petani',
            name='alamat',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
