# Generated by Django 5.1.6 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_remove_kesehatantanaman_penyakit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketuakelompok',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='petani',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
