# Generated by Django 5.1.6 on 2025-04-28 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_kesehatantanah_kadar_air_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='petani',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
