# Generated by Django 5.1.6 on 2025-05-02 13:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_lahan_created_at_petani_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilGapoktan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.CharField(default='Gapoktan Mlandingan', max_length=100)),
                ('gambar_kantor', models.ImageField(blank=True, null=True, upload_to='gambar/profil/kantor/')),
                ('deskripsi_kantor', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gambar_ketua', models.ImageField(blank=True, null=True, upload_to='gambar/profil/ketua/')),
                ('deskripsi_ketua', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Profil Gapoktan',
            },
        ),
    ]
