# Generated by Django 5.1.6 on 2025-05-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_profilgapoktan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=100)),
                ('tujuan', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('progres', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('berjalan', 'Berjalan'), ('selesai', 'Selesai')], default='berjalan', max_length=10)),
                ('dokumentasi', models.ImageField(blank=True, null=True, upload_to='dokumentasi/')),
            ],
        ),
    ]
