# Generated by Django 5.1.6 on 2025-05-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_proyek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyek',
            options={'verbose_name_plural': 'Data Proyek'},
        ),
        migrations.DeleteModel(
            name='KesehatanTanah',
        ),
    ]
