# Generated by Django 5.1.6 on 2025-05-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_proyek_options_delete_kesehatantanah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyek',
        ),
    ]
