# Generated by Django 5.1.6 on 2025-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_delete_proyek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alsintan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=100)),
                ('jenis_alat', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('kondisi', models.CharField(choices=[('tersedia', 'Tersedia'), ('dipinjam', 'Dipinjam'), ('rusak', 'Rusak')], default='tersedia', max_length=10)),
                ('tanggal_pengadaan', models.DateField()),
                ('sumber_dana', models.CharField(blank=True, max_length=100, null=True)),
                ('dokumentasi', models.ImageField(blank=True, null=True, upload_to='gambar/alsintan/')),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Alsintan',
            },
        ),
    ]
