# Generated by Django 5.1.6 on 2025-05-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_alsintan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistribusiPupuk',
        ),
    ]
