# Generated by Django 5.1.6 on 2025-05-15 15:08

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_delete_distribusipupuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataERDKK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komoditas', models.CharField(max_length=100)),
                ('luas_lahan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jenis_pupuk', models.CharField(max_length=100)),
                ('jumlah_kebutuhan', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tahun_rencana', models.PositiveIntegerField(default=2025)),
                ('catatan', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.petani')),
            ],
            options={
                'verbose_name_plural': 'Data ERDKK',
            },
        ),
    ]
