# Generated by Django 5.1.6 on 2025-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_dataerdkk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataerdkk',
            name='jenis_pupuk',
        ),
        migrations.AlterField(
            model_name='dataerdkk',
            name='jumlah_kebutuhan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataerdkk',
            name='luas_lahan',
            field=models.CharField(max_length=20),
        ),
    ]
