# Generated by Django 5.1.6 on 2025-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_remove_dataerdkk_jenis_pupuk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataerdkk',
            name='jenis_pupuk',
            field=models.CharField(choices=[('NPK', 'NPK'), ('UREA', 'Urea'), ('ORGANIK', 'Organik')], default='NPK', max_length=20),
        ),
    ]
