# Generated by Django 5.1.6 on 2025-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_dataerdkk_jenis_pupuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Data Kegiatan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
