# Generated by Django 5.1.6 on 2025-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='kegiatan/'),
        ),
    ]
