# Generated by Django 5.1.6 on 2025-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_kegiatan_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketuakelompok',
            name='email',
        ),
        migrations.RemoveField(
            model_name='petani',
            name='email',
        ),
        migrations.AddField(
            model_name='ketuakelompok',
            name='nik',
            field=models.CharField(default='0000000000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='petani',
            name='nik',
            field=models.CharField(default='0000000000000000', max_length=100),
        ),
    ]
