# Generated by Django 5.1.6 on 2025-05-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_forumdiskusi_komentardiskusi'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lahan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
