# Generated by Django 5.1.6 on 2025-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_lahan_latitude_lahan_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketuakelompok',
            name='grup',
        ),
        migrations.AddField(
            model_name='ketuakelompok',
            name='grup',
            field=models.ManyToManyField(related_name='ketua', to='administrator.grup'),
        ),
    ]
