# Generated by Django 5.1.6 on 2025-05-22 02:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_remove_ketuakelompok_grup_ketuakelompok_grup'),
    ]

    operations = [
        migrations.CreateModel(
            name='KetuaGapoktan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(default='0000000000000000', max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua_gapoktan', to='administrator.grup')),
            ],
            options={
                'verbose_name_plural': 'Ketua Gapoktan',
            },
        ),
    ]
