# Generated by Django 5.1.6 on 2025-05-31 07:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_alsintan_slug_kegiatan_slug_ketuagapoktan_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='tanggal_panen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lahan',
            name='tanggal_tanam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alsintan',
            name='keterangan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lahan',
            name='lokasi',
            field=models.CharField(default='belum di isi', max_length=100),
            preserve_default=False,
        ),
    ]
