# Generated by Django 5.1.6 on 2025-06-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_lahan_tanggal_panen_lahan_tanggal_tanam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotokopi_ktp', models.ImageField(upload_to='pengajuan/ktp/')),
                ('fotokopi_kk', models.ImageField(upload_to='pengajuan/kk/')),
                ('fotokopi_sppt', models.ImageField(upload_to='pengajuan/sppt/')),
                ('label_nama_ibu', models.ImageField(upload_to='pengajuan/label_ibu/')),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('petani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sppt', to='administrator.petani')),
            ],
        ),
    ]
