# Generated by Django 5.1.6 on 2025-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_remove_sppt_label_nama_ibu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppt',
            name='nama_ibu',
            field=models.CharField(default='Tidak Diketahui', max_length=100),
        ),
    ]
