# Generated by Django 5.1.6 on 2025-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_remove_sppt_petani'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppt',
            name='nama_petani',
            field=models.CharField(default='Tidak Diketahui', max_length=100),
        ),
    ]
