# Generated by Django 5.1.6 on 2025-06-24 07:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0034_sppt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketuagapoktan',
            name='grup',
        ),
        migrations.CreateModel(
            name='KetuaPoktan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(default='0000000000000000', max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua_poktan', to='administrator.grup')),
            ],
            options={
                'verbose_name_plural': 'Data Ketua Kelompok',
            },
        ),
        migrations.DeleteModel(
            name='KetuaKelompok',
        ),
        migrations.AddField(
            model_name='ketuagapoktan',
            name='grup',
            field=models.ManyToManyField(related_name='ketua_gapoktan', to='administrator.grup'),
        ),
    ]
