# Generated by Django 5.1.6 on 2025-06-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_remove_ketuagapoktan_grup_ketuapoktan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppt',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
