# Generated by Django 5.1.6 on 2025-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0036_sppt_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketuagapoktan',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
