# Generated by Django 5.1.6 on 2025-07-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_alter_ketuagapoktan_no_hp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kegiatan',
            options={'ordering': ['-tanggal'], 'verbose_name_plural': 'Data Kegiatan'},
        ),
        migrations.RenameField(
            model_name='alsintan',
            old_name='jenis_alat',
            new_name='pemilik',
        ),
    ]
