# Generated by Django 5.1.6 on 2025-07-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0038_alter_kegiatan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataerdkk',
            name='catatan',
        ),
    ]
