# Generated by Django 5.1.6 on 2025-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0039_remove_dataerdkk_catatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataerdkk',
            name='jenis_pupuk',
        ),
        migrations.RemoveField(
            model_name='dataerdkk',
            name='jumlah_kebutuhan',
        ),
        migrations.AddField(
            model_name='dataerdkk',
            name='pupuk_npk',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dataerdkk',
            name='pupuk_organik',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dataerdkk',
            name='pupuk_urea',
            field=models.FloatField(default=0),
        ),
    ]
