# Generated by Django 5.1.6 on 2025-07-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0040_remove_dataerdkk_jenis_pupuk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kesehatantanaman',
            old_name='kondisi',
            new_name='penyakit',
        ),
        migrations.RemoveField(
            model_name='kesehatantanaman',
            name='isi_penyakit_dan_tindakan',
        ),
    ]
