# Generated by Django 5.1.6 on 2025-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0042_rename_kesehatantanaman_penyakittanaman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahan',
            name='status_panen',
            field=models.CharField(choices=[('tertunda', 'Tertunda'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], default='tertunda', max_length=20),
        ),
    ]
