# Generated by Django 5.1.6 on 2025-07-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0043_lahan_status_panen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketuapoktan',
            name='no_hp',
        ),
    ]
