# Generated by Django 5.1.6 on 2025-07-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0044_remove_ketuapoktan_no_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketuagapoktan',
            name='no_hp',
        ),
    ]
