# Generated by Django 5.1.6 on 2025-07-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0045_remove_ketuagapoktan_no_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petani',
            name='no_hp',
        ),
    ]
